services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SimPod\KafkaBundle\Kafka\Configuration:
        arguments:
            $config: '%kafka%'

    SimPod\KafkaBundle\Console\ConsumeCommand:
    SimPod\KafkaBundle\Console\ConsumerListCommand:
