name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 17 * * *"

env:
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'
  LIBRDKAFKA_VERSION: v1.4.2

jobs:
  coding-standard:
    runs-on: ubuntu-18.04
    name: Coding Standard

    steps:
      - uses: actions/checkout@v2

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          coverage: none
          tools: pecl
          extensions: json, rdkafka

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install ${DEPENDENCIES}

      - name: Coding Standard
        run: vendor/bin/phpcs

  coverage:
    runs-on: ubuntu-18.04
    name: Code Coverage

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          coverage: pcov
          tools: pecl
          extensions: json, mbstring, rdkafka

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install ${DEPENDENCIES}

      - name: Code coverage
        run: |
          ./vendor/bin/phpunit --coverage-clover /tmp/coverage/clover.xml

      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_RUN_LOCALLY: 1
        run: vendor/bin/php-coveralls --coverage_clover /tmp/coverage/clover.xml --json_path /tmp/coverage/coveralls.json

  test_with-php-versions:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [7.4, 8.0]
        env: [
          'DEPENDENCIES=--prefer-lowest',
          '',
        ]
    name: PHP ${{ matrix.php }} Test ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v2

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: pecl
          extensions: json, mbstring, rdkafka

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install ${DEPENDENCIES}

      - name: Run tests
        run: |
          export $ENV
          ./vendor/bin/phpunit
        env:
          ENV: ${{ matrix.env}}
